version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123dev
      POSTGRES_DB: travelid
    networks:
      - travelid
  dev-redis:
    image: redis:alpine
    environment:
      REDIS_ARGS: "--requirepass travelid --user travelid on >password ~* allcommands --user default off nopass nocommands"
    ports:
      - 6379:6379
    networks:
      - travelid
networks:
  travelid: